global using Microsoft.Extensions.Options;
global using MongoDB.Driver;
global using SearchSyncService.Consumers;
global using SearchSyncService.Consumers.Models;
global using SearchSyncService.Models;
global using SearchSyncService.MongoDb.DataBase;
global using SearchSyncService.Options;
global using SearchSyncService.Services;
global using System.Text.Json;
